#!/bin/bash

# TODO: Update this script

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/roundcube
mkdir -p $backup_dir

sudo cp -a /var/www/roundcube/. $backup_dir/sources
sudo cp -a /etc/php5/fpm/pool.d/roundcube.conf $backup_dir/php-fpm.conf

db_pwd=$(sudo yunohost app setting roundcube mysqlpwd)
sudo mysqldump -u roundcube -p"$db_pwd" roundcube > $backup_dir/dump.sql

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/roundcube/. $backup_dir/yunohost
domain=$(sudo yunohost app setting roundcube domain)
sudo cp -a /etc/nginx/conf.d/$domain.d/roundcube.conf $backup_dir/nginx.conf
