#!/bin/bash
#### json
##{ 
##  "arguments": [ 
##    {
##      "name": "domain",
##      "ask": {
##        "en": "Choose a domain for Roundcube (i.e. mydomain.org)"
##      }
##    },
##    {
##      "name": "path",
##      "ask": {
##        "en": "Choose a path for Roundcube (i.e. /webmail)"
##      }
##    }
##  ]
##}
####

domain=$1
path=$2

if [[ ! -d /etc/nginx/conf.d/$domain.d ]]; then
    echo "Domain not found"
    exit 1
fi

if [[ ! "$path" =~ ^/ ]] ; then
    echo "Invalid path"
    exit 1
fi

deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

db_user=roundcube
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
db_name=roundcube
root_pwd=$(sudo cat /etc/yunohost/mysql)

mysql -u root -p$root_pwd -e "CREATE DATABASE $db_name ; GRANT ALL PRIVILEGES ON $db_name.* TO '$db_user'@localhost IDENTIFIED BY '$db_pwd';"
mysql -u $db_user -p$db_pwd $db_name < ../sources/SQL/mysql.initial.sql

sudo mkdir -p /var/www/roundcube
sudo cp -a ../sources/* /var/www/roundcube
sudo cp ../conf/main.inc.php /var/www/roundcube/config/
sudo cp ../conf/db.inc.php /var/www/roundcube/config/

sudo sed -i "s/rcmail-ynhDESkeyTOchange/$deskey/g" /var/www/roundcube/config/main.inc.php
sudo sed -i "s/yunouser/$db_user/g" /var/www/roundcube/config/db.inc.php
sudo sed -i "s/yunopass/$db_pwd/g" /var/www/roundcube/config/db.inc.php
sudo sed -i "s/yunobase/$db_name/g" /var/www/roundcube/config/db.inc.php

sudo chown -R www-data: /var/www/roundcube

sed -i "s@pathTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@/var/www/roundcube@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/roundcube.conf

sudo yunohost app setting swag domain -v $domain
sudo yunohost app setting swag path -v $path

sudo service nginx reload
sudo yunohost domain ssowatconf
