#!/bin/bash

db_user=roundcube
db_name=roundcube
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost setting roundcube domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user ;"
sudo rm -rf /var/www/roundcube
sudo rm -f /etc/nginx/conf.d/$domain.d/roundcube.conf
