#!/bin/bash

domain=$(sudo yunohost app setting roundcube domain)
path=$(sudo yunohost app setting roundcube path)

deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
db_user=roundcube
db_pwd=$(sudo yunohost app setting roundcube mysqlpwd)
db_file=../sources/SQL/mysql/$(ls -tr -1 ../sources/SQL/mysql | head -1)

mysql -u $db_user -p$db_pwd $db_user < $db_file

mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/automatic_addressbook/SQL/mysql.initial.sql

final_path=/var/www/roundcube
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo cp ../conf/main.inc.php $final_path/config/
sudo cp ../conf/main.inc.php $final_path/config/defaults.inc.php
sudo cp ../conf/db.inc.php $final_path/config/
sudo mv $final_path/plugins/managesieve/config.inc.php.dist $final_path/plugins/managesieve/config.inc.php

sudo sed -i "s/rcmail-ynhDESkeyTOchange/$deskey/g" $final_path/config/main.inc.php
sudo sed -i "s/yunouser/$db_user/g" $final_path/config/db.inc.php
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/config/db.inc.php
sudo sed -i "s/yunobase/$db_user/g" $final_path/config/db.inc.php

sudo mkdir -p $final_path/logs
sudo chown -R www-data: $final_path

sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/roundcube.conf

sed -i "s@NAMETOCHANGE@roundcube@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/roundcube.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

finalphpini=/etc/php5/fpm/conf.d/20-roundcube.ini
sudo cp ../conf/php-fpm.ini $finalphpini
sudo chown root: $finalphpini
sudo chmod 644 $finalphpini

sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
